- name: Pull image from repository
  docker_image:
    name: kencehz/yolofrontend:v1.0.0
    source: pull

- name: Create Node.js Frontend Container
  docker_container:
    name: yoloclientcontainer
    image: kencehz/yolofrontend:v1.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes