apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontendservice
  template:
    metadata:
      labels:
        app: frontendservice
    spec:
      containers:
      - name: frontendservice
        image: kencehz/yoloclient:v1.0.0
        ports:
        - containerPort: 5000
